### ISSUE TITLE
font awesome icons not working on IOS7 applications

### ISSUE THREAD

**Issue by ajimenezdev** [commadelimited/jQuery-Mobile-Icon-Pack#60]
I have a mobile application with Apache cordova.
I added font awesome to the application and all is working fine with browser and ios version under 7, but with IOS7 the font awesome icons are correct but the rest of the icons are not displaying in correct position.

If I removed the line <link rel="stylesheet" href="static/jqm-icon-pack-fa.css" /> from the code, obviously the font awesome icons not working, but the rest of the icons function ok again

**Comment by ajimenezdev** [comment]
I continue testing and it fails too with on safari browser for ios7 and chrome browser on Android device (Nexus 4 with android 4.3).

And not only fails my web application, if I try to access to http://andymatthews.net/code/jQuery-Mobile-Icon-Pack/font-awesome/ font awesome works perfectly but icon on back button is not display correctly

**Comment by ironicent** [comment]
I am seeing this too. Would someone be able to confirm and look at that?

**Comment by BenjaminKlatt** [comment]
With iOS7, Apple started to use a pixel ratio of 2. This change includes an issue of how background sizes are processed in context with css media queries. There is a good explanation about this at http://stackoverflow.com/questions/18950334/ios7-ignoring-retina-css-media-queries-background-size

The jQuery Mobile Icon Pack makes use of sprites and background image sizes in combination with media queries. This requires to fix this ratio-background-issue in the css.

``` css
@media
only screen and (-webkit-min-device-pixel-ratio: 2),
only screen and (-moz-min-device-pixel-ratio: 2),
only screen and (-o-min-device-pixel-ratio: 2/1),
only screen and (min-device-pixel-ratio: 2),
only screen and (min-resolution: 2dppx){

    .ui-icon-plus, .ui-icon-minus, .ui-icon-delete, .ui-icon-arrow-r,
    .ui-icon-arrow-l, .ui-icon-arrow-u, .ui-icon-arrow-d, .ui-icon-check,
    .ui-icon-gear, .ui-icon-refresh, .ui-icon-forward, .ui-icon-back,
    .ui-icon-grid, .ui-icon-star, .ui-icon-alert, .ui-icon-info2, .ui-icon-home, .ui-icon-search, .ui-icon-searchfield:after,
    .ui-icon-checkbox-off, .ui-icon-checkbox-on, .ui-icon-radio-off, .ui-icon-radio-on, .ui-icon-email , .ui-icon-page,
    .ui-icon-question , .ui-icon-foursquare, .ui-icon-dollar , .ui-icon-euro,
    .ui-icon-pound , .ui-icon-apple , .ui-icon-chat , .ui-icon-trash , .ui-icon-mappin , .ui-icon-direction,
    .ui-icon-heart , .ui-icon-wrench , .ui-icon-play , .ui-icon-pause , .ui-icon-stop , .ui-icon-person , .ui-icon-music,
    .ui-icon-wifi , .ui-icon-phone , .ui-icon-power ,
    .ui-icon-lightning , .ui-icon-drink , .ui-icon-android {
        -moz-background-size: 774px 54px;
        -o-background-size: 774px 54px;
        -webkit-background-size: 774px 54px;
        background-size: 774px 54px;
    }
    .ui-icon:before { margin-left: 4px; }
}
```

I also summarized this at http://www.bar54.de/blog/2013/12/jquery-mobile-icon-pack-and-ios-7-retina-devices/

I hope this helps and I would be happy to see this fix build into the next release of the icon pack.

br
benjamin
